force-app/main/default/objects/Excercise__c/Excercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Excercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Excercise__c/fields/isTime__c.field-meta.xml
<CustomField>
    <fullName>isTime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Excercise__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ExcerciseInTrain__c/ExcerciseInTrain__c.object-meta.xml
<CustomObject>
    <label>ExcerciseInTrain</label>
    <nameField>
        <label>Excercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExcerciseInTrains</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ExcerciseInTrain__c/fields/Excercise__c.field-meta.xml
<CustomField>
    <fullName>Excercise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Excercise</label>
    <referenceTo>Excercise__c</referenceTo>
    <relationshipLabel>ExcerciseInTrains</relationshipLabel>
    <relationshipName>ExcerciseInTrains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExcerciseInTrain__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExcerciseInTrain__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>ExcerciseInTrains</relationshipLabel>
    <relationshipName>ExcerciseInTrains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Train Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Train__c/fields/TrainingDate__c.field-meta.xml
<CustomField>
    <fullName>TrainingDate__c</fullName>
    <formula>DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TrainingDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Train.cls
global with sharing class Train {
    @AuraEnabled(cacheable=true)
    global static List<Train__c> getTrains(){
        return [SELECT Id,Name,TrainingDate__c, (SELECT id,Excercise__r.name, Count__c,Time__c  FROM ExcerciseInTrains__r) FROM Train__c WHERE Id IN (SELECT Train__c FROM ExcerciseInTrain__c) ORDER BY CreatedDate];
    }

    @AuraEnabled(cacheable=true)
    global static List<Excercise__c> getExercises(){
        return [SELECT Id,Name,isCount__c,isTime__c, Picture__c, Rating__c FROM Excercise__c ORDER BY Rating__c DESC];
    }

    @AuraEnabled(cacheable=true)
    global static List<Excercise__c> findExercises(String nameExcer){
        return [SELECT Id,Name,isCount__c,isTime__c, Picture__c FROM Excercise__c WHERE Name LIKE : nameExcer ORDER BY Rating__c DESC];
    }



}